apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
    project: {{ .Values.projectName }}
  ports:
    - protocol: TCP
      port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}